cmake_minimum_required(VERSION 3.25)
foreach(required VCF_PACKAGE_SOURCE VCF_PACKAGE_BINARY VCF_PACKAGE_GENERATOR VCF_PACKAGE_C_COMPILER VCF_PACKAGE_CXX_COMPILER VCF_PACKAGE_CTEST_COMMAND)
 if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
  message(FATAL_ERROR "Missing ${required}")
 endif()
endforeach()
function(run_checked)
 execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
 if(NOT status EQUAL 0)
  message(FATAL_ERROR "SDK package check failed (${status}):\n${output}\n${errors}")
 endif()
endfunction()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(work "${VCF_PACKAGE_BINARY}/sdk-package-test-${suffix}")
file(MAKE_DIRECTORY "${work}")
run_checked("${CMAKE_COMMAND}" --install "${VCF_PACKAGE_BINARY}" --component sdk --prefix "${work}/staging" --config "${VCF_PACKAGE_CONFIG}")
# Check a renamed SDK in a path containing spaces. No source-tree include paths
# are passed to this consumer. The generated staging directory is now absent.
file(REAL_PATH "${VCF_PACKAGE_BINARY}" owned_root)
file(REAL_PATH "${work}/staging/sdk" from)
set(to "${work}/relocated dependency")
cmake_path(IS_PREFIX owned_root "${from}" NORMALIZE from_owned)
cmake_path(IS_PREFIX owned_root "${to}" NORMALIZE to_owned)
if(NOT from_owned OR NOT to_owned)
 message(FATAL_ERROR "SDK relocation must remain inside its owned build directory")
endif()
file(RENAME "${from}" "${to}")
file(COPY "${VCF_PACKAGE_SOURCE}/tests/native/sdk-package/" DESTINATION "${work}/consumer")
run_checked("${CMAKE_COMMAND}" -S "${work}/consumer" -B "${work}/consumer-build" -G "${VCF_PACKAGE_GENERATOR}"
 "-DCMAKE_PREFIX_PATH=${to}" "-DCMAKE_C_COMPILER=${VCF_PACKAGE_C_COMPILER}" "-DCMAKE_CXX_COMPILER=${VCF_PACKAGE_CXX_COMPILER}"
 "-DCMAKE_MAKE_PROGRAM=${VCF_PACKAGE_MAKE_PROGRAM}" "-DCMAKE_BUILD_TYPE=${VCF_PACKAGE_CONFIG}"
 -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF)
run_checked("${CMAKE_COMMAND}" --build "${work}/consumer-build" --config "${VCF_PACKAGE_CONFIG}")
run_checked("${VCF_PACKAGE_CTEST_COMMAND}" --test-dir "${work}/consumer-build" -C "${VCF_PACKAGE_CONFIG}" --output-on-failure)
message(STATUS "Relocated SDK: standalone C and C++ consumers configured, built and ran without a provider.")
