#include <oni/vcf/core.hpp>
#include <array>
namespace oni::vcf {
namespace {
const CatalogEntry entries[] = {
 {"chest", "storage", "remoteworkstations.open.chest", "chest", "block", 27, false},
 {"doublechest", "storage", "remoteworkstations.open.doublechest", "doublechest", "block", 54, false},
 {"hopper", "storage", "remoteworkstations.open.hopper", "hopper", "block", 5, false},
 {"dispenser", "storage", "remoteworkstations.open.dispenser", "dispenser", "block", 9, false},
 {"barrel", "storage", "remoteworkstations.open.barrel", "barrel", "block", 27, false},
 {"dropper", "storage", "remoteworkstations.open.dropper", "dropper", "block", 9, false},
 {"trappedchest", "storage", "remoteworkstations.open.trappedchest", "trappedchest", "block", 27, false},
 {"enderchest", "storage", "remoteworkstations.open.enderchest", "enderchest|ec", "player", 27, false},
 {"shulker", "storage", "remoteworkstations.open.shulker", "shulker", "held-item", 27, false},
 {"craft", "workstation", "remoteworkstations.open.craft", "craft|workbench", "player", 10, false},
 {"anvil", "workstation", "remoteworkstations.open.anvil", "anvil", "player", 3, false},
 {"grindstone", "workstation", "remoteworkstations.open.grindstone", "grindstone", "player", 3, false},
 {"smithing", "workstation", "remoteworkstations.open.smithing", "smithing", "player", 4, false},
 {"stonecutter", "workstation", "remoteworkstations.open.stonecutter", "stonecutter", "player", 2, false},
 {"loom", "workstation", "remoteworkstations.open.loom", "loom", "player", 4, false},
 {"cartography", "workstation", "remoteworkstations.open.cartography", "cartography", "player", 3, false},
 {"enchanting", "workstation", "remoteworkstations.open.enchanting", "enchanting|etable", "block", 2, false},
 {"furnace", "workstation", "remoteworkstations.open.furnace", "furnace", "block", 3, false},
 {"blastfurnace", "workstation", "remoteworkstations.open.blastfurnace", "blastfurnace", "block", 3, false},
 {"smoker", "workstation", "remoteworkstations.open.smoker", "smoker", "block", 3, false},
 {"brewing", "workstation", "remoteworkstations.open.brewing", "brewing", "block", 5, false},
 {"beacon", "workstation", "remoteworkstations.open.beacon", "beacon", "block", 1, false},
 {"crafter", "workstation", "remoteworkstations.open.crafter", "crafter", "block", 9, false},
 {"lectern", "contextual", "remoteworkstations.open.lectern", "", "block", 0, false},
 {"writtenbook", "contextual", "remoteworkstations.open.writtenbook", "", "held-item", 0, false},
 {"bookediting", "contextual", "remoteworkstations.open.bookediting", "", "held-item", 0, false},
 {"villager", "contextual", "remoteworkstations.open.villager", "", "entity", 3, false},
 {"wanderingtrader", "contextual", "remoteworkstations.open.wanderingtrader", "", "entity", 3, false},
 {"horse", "contextual", "remoteworkstations.open.horse", "", "entity", 0, false},
 {"donkey", "contextual", "remoteworkstations.open.donkey", "", "entity", 0, false},
 {"mule", "contextual", "remoteworkstations.open.mule", "", "entity", 0, false},
 {"llama", "contextual", "remoteworkstations.open.llama", "", "entity", 0, false},
 {"traderllama", "contextual", "remoteworkstations.open.traderllama", "", "entity", 0, false},
 {"chestboat", "contextual", "remoteworkstations.open.chestboat", "", "entity", 0, false},
 {"chestminecart", "contextual", "remoteworkstations.open.chestminecart", "", "entity", 0, false},
 {"hopperminecart", "contextual", "remoteworkstations.open.hopperminecart", "", "entity", 0, false},
 {"camel", "contextual", "remoteworkstations.open.camel", "", "entity", 0, false},
 {"camelhusk", "contextual", "remoteworkstations.open.camelhusk", "", "entity", 0, false},
 {"zombiehorse", "contextual", "remoteworkstations.open.zombiehorse", "", "entity", 0, false},
 {"skeletonhorse", "contextual", "remoteworkstations.open.skeletonhorse", "", "interaction-only", 0, false},
 {"nautilus", "contextual", "remoteworkstations.open.nautilus", "", "entity", 0, false},
 {"zombienautilus", "contextual", "remoteworkstations.open.zombienautilus", "", "entity", 0, false},
 {"allay", "contextual", "remoteworkstations.open.allay", "", "interaction-only", 0, false},
 {"panda", "contextual", "remoteworkstations.open.panda", "", "interaction-only", 0, false},
 {"piglin", "contextual", "remoteworkstations.open.piglin", "", "interaction-only", 0, false},
 {"agent", "contextual", "remoteworkstations.open.agent", "", "entity", 0, false},
 {"sign", "editor", "remoteworkstations.open.sign", "", "block-editor", 0, true},
 {"npc", "editor", "remoteworkstations.open.npc", "", "entity-dialogue", 0, false},
 {"commandblock", "editor", "remoteworkstations.open.commandblock", "", "block-editor", 0, true},
 {"commandblockminecart", "editor", "remoteworkstations.open.commandblockminecart", "", "entity-editor", 0, true},
 {"structure", "editor", "remoteworkstations.open.structure", "", "block-editor", 0, true},
 {"jigsaw", "editor", "remoteworkstations.open.jigsaw", "", "block-editor", 0, true},
 {"compoundcreator", "education", "remoteworkstations.open.compoundcreator", "", "block", 0, false},
 {"elementconstructor", "education", "remoteworkstations.open.elementconstructor", "", "block", 0, false},
 {"materialreducer", "education", "remoteworkstations.open.materialreducer", "", "block", 0, false},
 {"labtable", "education", "remoteworkstations.open.labtable", "", "block", 0, false},
 {"inventory2x2", "embedded-or-interaction", "remoteworkstations.open.inventory2x2", "", "embedded", 0, false},
 {"armor", "embedded-or-interaction", "remoteworkstations.open.armor", "", "embedded", 0, false},
 {"offhand", "embedded-or-interaction", "remoteworkstations.open.offhand", "", "embedded", 0, false},
 {"cursor", "embedded-or-interaction", "remoteworkstations.open.cursor", "", "embedded", 0, false},
 {"recipebook", "embedded-or-interaction", "remoteworkstations.open.recipebook", "", "embedded", 0, false},
 {"bundle", "embedded-or-interaction", "remoteworkstations.open.bundle", "", "held-item", 0, false},
 {"hud", "embedded-or-interaction", "remoteworkstations.open.hud", "", "embedded", 0, false},
 {"cauldron", "embedded-or-interaction", "remoteworkstations.open.cauldron", "", "interaction-only", 0, false},
 {"jukebox", "embedded-or-interaction", "remoteworkstations.open.jukebox", "", "interaction-only", 0, false},
 {"decoratedpot", "embedded-or-interaction", "remoteworkstations.open.decoratedpot", "", "interaction-only", 0, false},
 {"fletching", "embedded-or-interaction", "remoteworkstations.open.fletching", "", "interaction-only", 0, false},
 {"campfire", "embedded-or-interaction", "remoteworkstations.open.campfire", "", "interaction-only", 0, false},
 {"composter", "embedded-or-interaction", "remoteworkstations.open.composter", "", "interaction-only", 0, false},
};
}
std::span<const CatalogEntry> catalog(){return entries;}
const CatalogEntry* resolve(std::string_view id){
 for(const auto&row:entries){
  if(row.id==id)return &row;
  auto rest=row.aliases;while(!rest.empty()){auto split=rest.find('|');if(rest.substr(0,split)==id)return &row;if(split==std::string_view::npos)break;rest.remove_prefix(split+1);}
 }return nullptr;
}
}
