# Header-only public SDK, using the exact source already audited for the runtime.
# Do not add Endstone's runtime subprojects or link Python.
if(NOT EXISTS "${VCF_ENDSTONE_ROOT}/include/endstone/plugin/plugin.h")
 message(FATAL_ERROR "Provide VCF_ENDSTONE_ROOT for pinned 8f84d6f5b556916597ed5b6b71329b2ed3ca8fc8")
endif()
if(NOT EXISTS "${VCF_EXPECTED_ROOT}/include/nonstd/expected.hpp")
 message(FATAL_ERROR "Provide VCF_EXPECTED_ROOT for expected-lite 0.9.0")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/VerifyEndstoneHeaders.cmake")
file(SHA256 "${VCF_EXPECTED_ROOT}/include/nonstd/expected.hpp" expected_hash)
if(NOT expected_hash STREQUAL "bbab48a56231800c21373be71e47f1b9d8d4e8e10e2c9d3a51c4f5f850104086")
 message(FATAL_ERROR "expected-lite hash mismatch")
endif()
function(vcf_generate_sdk_version)
 set(PROJECT_VERSION_MAJOR 0)
 set(PROJECT_VERSION_MINOR 11)
 set(PROJECT_VERSION_PATCH 10)
 set(ENDSTONE_VERSION_FULL "0.11.10")
 configure_file("${VCF_ENDSTONE_ROOT}/include/endstone/version.h.in" "${CMAKE_CURRENT_BINARY_DIR}/generated/endstone/version.h" @ONLY)
endfunction()
vcf_generate_sdk_version()
add_library(endstone_sdk INTERFACE)
target_include_directories(endstone_sdk INTERFACE "${VCF_ENDSTONE_ROOT}/include" "${VCF_EXPECTED_ROOT}/include" "${CMAKE_CURRENT_BINARY_DIR}/generated")

if(NOT WIN32)
 get_filename_component(vcf_dependency_parent "${VCF_EXPECTED_ROOT}" DIRECTORY)
 set(VCF_ENTT_ROOT "${vcf_dependency_parent}/entt" CACHE PATH "Pinned EnTT 3.16.0 private NBT header dependency")
 include("${CMAKE_CURRENT_LIST_DIR}/VerifyBedrockNbtHeaders.cmake")
 add_library(bedrock_nbt_headers INTERFACE)
 target_include_directories(bedrock_nbt_headers INTERFACE "${VCF_ENDSTONE_ROOT}/src" "${VCF_ENTT_ROOT}/src")
 target_link_libraries(bedrock_nbt_headers INTERFACE endstone_sdk)
endif()
